sudo: required
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install --user -r requirements.txt
  - pip install --user -r tests-requirements.txt
  - pip install .
# command to run tests
script: pytest
