language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r tests-requirements.txt
  - pip install .
# command to run tests
script: pytest
after_success:
  - pytest --cov-report term --cov-report xml  --cov=pyzzy tests/
  - codecov
